# -*- coding: utf-8 -*-
"""c105

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B3qNwCwPCao9ZbvdAl1iBJqEVV45N7D8
"""

from google.colab import files
data_to_load = files.upload()

import csv 
with open ("class1.csv", newline="") as f:
    reader = csv.reader(f)
    file_data = list(reader)
    
file_data.pop(0)
total_marks = 0
total_entries = len(file_data)
for marks in file_data: total_marks+=float(marks[1])

mean = total_marks/total_entries
print(str (mean))
import pandas as pd
import plotly.express as px
df = pd.read_csv("class1.csv")
fig = px.scatter(df, x = "Student Number", y = "Marks")
fig.update_layout(shapes = [
    dict(
        type = "line", y0 = mean, y1 = mean, x0 = 0, x1 = total_entries 
    )
])

fig.show()

from google.colab import files
data_to_load = files.upload()

import csv 
with open ("class2.csv", newline="") as f:
    reader = csv.reader(f)
    file_data = list(reader)
    
file_data.pop(0)
total_marks = 0
total_entries = len(file_data)
for marks in file_data: total_marks+=float(marks[1])

mean = total_marks/total_entries
print(str (mean))
import pandas as pd
import plotly.express as px
df = pd.read_csv("class2.csv")
fig = px.scatter(df, x = "Student Number", y = "Marks")
fig.update_layout(shapes = [
    dict(
        type = "line", y0 = mean, y1 = mean, x0 = 0, x1 = total_entries 
    )
])

fig.show()



from google.colab import files
data_to_load = files.upload()



import math



# list of elements to calculate mean
import csv
with open('data.csv', newline='') as f:
    reader = csv.reader(f)
    file_data = list(reader)


data = file_data[0]

#getting the mean
# data = [20,69,56,90,40,99,86,100,70,69,80,65,57,82,90,70,79,39,90,80,86,53,97,95,88,47,100,56,97,100] #list of x or y
# data=[60,61,65,63,98,99,90,95,91,96]

# finding mean
def mean(data):
    n= len(data)
    total =0
    for x in data:
        total += int(x)

    mean = total / n
    return mean



# squaring and getting the values
squared_list= []
for number in data:
    a = int(number) - mean(data)
    a= a**2
    squared_list.append(a)

#getting sum
sum =0
for i in squared_list:
    sum =sum + i

#dividing the sum by the total values
result = sum/ (len(data)-1)

# getting the deviation by taking square root of the result
std_deviation = math.sqrt(result)
print(std_deviation)
# print("derived using predefined function ",statistics.stdev(data))